/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleCategoria;
import controle.ControlePessoa;
import controle.ControleSubcategoria;
import controle.ControleTitulo;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import modelo.Categoria;
import modelo.Pessoa;
import modelo.Subcategoria;
import modelo.Titulo;
import modelo.TipoTitulo;

/**
 *
 * @author macbook
 */
public class AddTitulo extends javax.swing.JPanel {

    List<Categoria> listaCategoria;
    List<Subcategoria> listaSubcategoria;
    List<Pessoa> listaPessoa;
    ArrayList<Titulo> resultadoPesquisa;

    public AddTitulo() throws ParseException {
        initComponents();
        atualizarPesquisa();
        formatarCampos();

        //Combobox de categoria
        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
        ControleCategoria controlador = new ControleCategoria();
        listaCategoria = controlador.getCategoria();
        for (int i = 0; i < listaCategoria.size(); i++) {
            cbCategorias.addItem(listaCategoria.get(i).getNomeCategoria());
        }

        //Combobox de pessoas
        cbCedente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
        ControlePessoa controladorPessoa = new ControlePessoa();
        listaPessoa = controladorPessoa.getPessoa();
        for (int i = 0; i < listaPessoa.size(); i++) {
            cbCedente.addItem(listaPessoa.get(i).getNomePessoa());
        }

    }

    //--------------MÉTODOS-------------------
    private void atualizarPesquisa() {
        ControleTitulo controle = new ControleTitulo();
        DefaultTableModel model = (DefaultTableModel) tblEditTitulo.getModel();
        model.setNumRows(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        try {
            this.resultadoPesquisa = controle.pesquisar(tfPesquisa.getText().trim());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Falha na Pesquisa!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        for (Titulo titulo : this.resultadoPesquisa) {
            model.addRow(new Object[]{
                titulo.getNomeTitulo(),
                titulo.getValorTitulo(),
                titulo.getNumeroParcela(),
                titulo.getDataVencimento() != null ? sdf.format(titulo.getDataVencimento()) : null,
                titulo.getDataRealizacao() != null ? sdf.format(titulo.getDataRealizacao()) : null,
                titulo.getPendente(),
                titulo.getPessoa().getNomePessoa(),
                titulo.getCedente(),});
        };
    }

    private void formatarCampos() {

        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.install(tfVencimento);
            MaskFormatter mascara2 = new MaskFormatter("##/##/####");
            mascara2.install(tfRealizacao);

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo de texto", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        tfTitulo = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        cbCategorias = new javax.swing.JComboBox<>();
        cbSubcategoria = new javax.swing.JComboBox<>();
        pnlInf = new javax.swing.JPanel();
        tfCedente = new javax.swing.JTextField();
        tfValor = new javax.swing.JTextField();
        tfRealizacao = new javax.swing.JFormattedTextField();
        cbCedente = new javax.swing.JComboBox<>();
        tfVencimento = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditTitulo = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        btPesquisa = new javax.swing.JButton();
        tfPesquisa = new javax.swing.JTextField();
        tfParcela = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Título ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N

        grupoTipo.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Despesa");
        jRadioButton2.setActionCommand("0");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        grupoTipo.add(jRadioButton1);
        jRadioButton1.setText("Receita");
        jRadioButton1.setActionCommand("1");

        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N
        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });

        cbSubcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cbSubcategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subcategoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N

        pnlInf.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlInf.setOpaque(false);

        tfCedente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedente/Sacado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N
        tfCedente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCedenteActionPerformed(evt);
            }
        });

        tfValor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor (R$)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N

        tfRealizacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Realização em caixa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N

        cbCedente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCedente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagador/Beneficiário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N

        tfVencimento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vencimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N
        tfVencimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfVencimentoMouseClicked(evt);
            }
        });

        tblEditTitulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Valor", "Parcela", "Vencimento", "Realizado", "Situação", "Beneficiario", "Cedente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEditTitulo);
        if (tblEditTitulo.getColumnModel().getColumnCount() > 0) {
            tblEditTitulo.getColumnModel().getColumn(1).setMinWidth(60);
            tblEditTitulo.getColumnModel().getColumn(1).setMaxWidth(61);
            tblEditTitulo.getColumnModel().getColumn(2).setMinWidth(60);
            tblEditTitulo.getColumnModel().getColumn(2).setMaxWidth(61);
            tblEditTitulo.getColumnModel().getColumn(5).setMinWidth(60);
            tblEditTitulo.getColumnModel().getColumn(5).setMaxWidth(61);
        }

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btPesquisa.setText("Pesquisa");

        tfParcela.setText("1");
        tfParcela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcelas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N

        javax.swing.GroupLayout pnlInfLayout = new javax.swing.GroupLayout(pnlInf);
        pnlInf.setLayout(pnlInfLayout);
        pnlInfLayout.setHorizontalGroup(
            pnlInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfLayout.createSequentialGroup()
                        .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfLayout.createSequentialGroup()
                        .addGroup(pnlInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfLayout.createSequentialGroup()
                                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbCedente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCedente)
                            .addGroup(pnlInfLayout.createSequentialGroup()
                                .addComponent(tfVencimento)
                                .addGap(18, 18, 18)
                                .addComponent(tfRealizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlInfLayout.setVerticalGroup(
            pnlInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfLayout.createSequentialGroup()
                .addGroup(pnlInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCedente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRealizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btPesquisa)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Nexa Light", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRAR NOVO TÍTULO");

        jLayeredPane1.setLayer(tfTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbCategorias, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbSubcategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pnlInf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfTitulo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(280, 280, 280))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(481, 481, 481))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2))
                    .addComponent(cbSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgDesfocado.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed

        //filtrando combobox Subcategoria a partir do índice categoria
        cbSubcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
        ControleSubcategoria controlador = new ControleSubcategoria();
        try {
            listaSubcategoria = controlador.getSubcategoria(cbCategorias.getSelectedIndex());
        } catch (SQLException ex) {
            Logger.getLogger(AddTitulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < listaSubcategoria.size(); i++) {
            cbSubcategoria.addItem(listaSubcategoria.get(i).getNomeSubcategoria());
        }
    }//GEN-LAST:event_cbCategoriasActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Titulo titulo = new Titulo();
        int iCat = cbCategorias.getSelectedIndex();
        int iPess = cbCedente.getSelectedIndex();
        int iSubcat = cbSubcategoria.getSelectedIndex();

        if (iSubcat < 0) {
            JOptionPane.showMessageDialog(this, "Subcategoria é um campo obrigatório!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        titulo.setNomeTitulo(tfTitulo.getText());
        titulo.setCedente(tfCedente.getText());

        try {
            titulo.setValorTitulo(Double.parseDouble(tfValor.getText()));
        } catch (NumberFormatException num) {
            JOptionPane.showMessageDialog(this, "Campo valor inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

        //Formatação de data, e verifica se há campo em branco
        try {
            if (!tfRealizacao.getText().trim().startsWith("/")) {
                Date temp = new SimpleDateFormat("dd/MM/yyyy").parse(tfRealizacao.getText());
                titulo.setDataRealizacao(temp);
            }
        } catch (ParseException ex) {
            Logger.getLogger(AddTitulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Formatação de data, e verifica se há campo em branco
        try {
            if (tfVencimento.getText().length() >= 8) {
                Date temp = new SimpleDateFormat("dd/MM/yyyy").parse(tfVencimento.getText());
                titulo.setDataVencimento(temp);
            };

        } catch (ParseException ex) {
            Logger.getLogger(AddTitulo.class.getName()).log(Level.SEVERE, null, ex);
        }

        TipoTitulo tipo = new TipoTitulo();
        tipo.setIdTipoTitulo(Integer.parseInt(grupoTipo.getSelection().getActionCommand()));
        titulo.setTipoTitulo(tipo);

        //combobox categoria/subcategora, salvando posição selecionada da lista e recuperando objeto:
        Categoria categoria = new Categoria();
        categoria.setIdCategoria(listaCategoria.get(iCat - 1).getIdCategoria());
        titulo.setCategoria(categoria);
        Subcategoria subcategoria = new Subcategoria();
        subcategoria.setIdSubcategoria(listaSubcategoria.get(iSubcat - 1).getIdSubcategoria());
        titulo.setSubCategoria(subcategoria);

        //combobox pessoa, salvando posição selecionada da lista e recuperando objeto:
        Pessoa pess = new Pessoa();
        pess.setIdPessoa(listaPessoa.get(iPess - 1).getIdPessoa());
        titulo.setPessoa(pess);

        titulo.setCedente(tfCedente.getText());
        titulo.setNumeroParcela(Integer.parseInt(tfParcela.getText()));
        titulo.setPendente("Pendente");

        //salvando titulo
        ControleTitulo controle = new ControleTitulo();
        try {
            controle.salvar(titulo);
            //setando o campos em branco novamente
            tfTitulo.setText("");
            tfCedente.setText("");
            tfValor.setText("");
            tfRealizacao.setText("");
            tfVencimento.setText("");
            cbCedente.setSelectedIndex(-1);
            cbCategorias.setSelectedIndex(-1);
            cbSubcategoria.setSelectedIndex(-1);
            jRadioButton2.setSelected(true);

        } catch (SQLException ex) {
            Logger.getLogger(AddTitulo.class.getName()).log(Level.SEVERE, null, ex);
        }

    atualizarPesquisa();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfCedenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCedenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCedenteActionPerformed

    private void tfVencimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfVencimentoMouseClicked

    }//GEN-LAST:event_tfVencimentoMouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JComboBox<String> cbCedente;
    private javax.swing.JComboBox<String> cbSubcategoria;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlInf;
    private javax.swing.JTable tblEditTitulo;
    private javax.swing.JTextField tfCedente;
    private javax.swing.JTextField tfParcela;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JFormattedTextField tfRealizacao;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JTextField tfValor;
    private javax.swing.JFormattedTextField tfVencimento;
    // End of variables declaration//GEN-END:variables
}
