/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleCategoria;
import controle.ControleSubcategoria;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Subcategoria;

/**
 *
 * @author macbook
 */
public class CategoriaView extends javax.swing.JPanel {

    ArrayList<Categoria> resultadoPesquisaCategoria;
    ArrayList<Subcategoria> resultadoPesquisaSub;

    /**
     * Creates new form CategoriaView
     */
    public CategoriaView() {
        initComponents();
        atualizarPesquisaCategoria();
        atualizarPesquisaSubcategoria();
    }

    // --------------------MÉTODOS ------------------------
    private void atualizarPesquisaCategoria() {
        ControleCategoria controle = new ControleCategoria();
        DefaultTableModel model = (DefaultTableModel) tblCategoria.getModel();
        model.setNumRows(0);

        try {
            this.resultadoPesquisaCategoria = controle.pesquisar(tfPesquisa.getText().trim());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Falha na Pesquisa!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        for (Categoria categoria : this.resultadoPesquisaCategoria) {
            model.addRow(new Object[]{
                categoria.getNomeCategoria(),
                categoria.getTipoCategoria()
            });
        }
        //combo box de categorias p/ classificacao de subcategorias
        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
        List<Categoria> listaCategorias = resultadoPesquisaCategoria;
        for (int i = 0; i < listaCategorias.size(); i++) {
            cbCategorias.addItem(listaCategorias.get(i).getNomeCategoria());
        }

    }

    private void atualizarPesquisaSubcategoria() {
        ControleSubcategoria controle = new ControleSubcategoria();
        DefaultTableModel model = (DefaultTableModel) tblSubcategoria.getModel();
        model.setNumRows(0);

        try {
            this.resultadoPesquisaSub = controle.pesquisar(tfPesquisaSub.getText().trim());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Falha na Pesquisa!", "ERRO", JOptionPane.ERROR_MESSAGE);

        }
        for (Subcategoria subcategoria : this.resultadoPesquisaSub) {
            model.addRow(new Object[]{
                subcategoria.getNomeCategoriaSubcategoria(),
                subcategoria.getNomeSubcategoria(),
                subcategoria.getNomeTipoSubcategoria()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        bgImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlSubcategoria = new javax.swing.JPanel();
        cbCategorias = new javax.swing.JComboBox<>();
        tfSubcategoria = new javax.swing.JTextField();
        btInserirSubcat = new javax.swing.JButton();
        pnlCategoria = new javax.swing.JPanel();
        tfCategoria = new javax.swing.JTextField();
        rbReceita = new javax.swing.JRadioButton();
        rbDespesa = new javax.swing.JRadioButton();
        btInserirCat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCategoria = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubcategoria = new javax.swing.JTable();
        tfPesquisa = new javax.swing.JTextField();
        btPesquisaCategoria = new javax.swing.JButton();
        btApagarCategoria = new javax.swing.JButton();
        tfPesquisaSub = new javax.swing.JTextField();
        btPesquisaSub = new javax.swing.JButton();
        btApagarSubcategoria = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 630));
        setMinimumSize(new java.awt.Dimension(1280, 630));
        setPreferredSize(new java.awt.Dimension(1280, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgDesfocado.jpg"))); // NOI18N

        jPanel1.setOpaque(false);

        pnlSubcategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova Subcategoria"));
        pnlSubcategoria.setOpaque(false);

        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategorias.setSelectedIndex(-1);
        cbCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N
        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });

        tfSubcategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subcategoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N

        btInserirSubcat.setText("Inserir");
        btInserirSubcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirSubcatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubcategoriaLayout = new javax.swing.GroupLayout(pnlSubcategoria);
        pnlSubcategoria.setLayout(pnlSubcategoriaLayout);
        pnlSubcategoriaLayout.setHorizontalGroup(
            pnlSubcategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubcategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btInserirSubcat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlSubcategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSubcategoriaLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(tfSubcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlSubcategoriaLayout.setVerticalGroup(
            pnlSubcategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubcategoriaLayout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addGroup(pnlSubcategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserirSubcat)))
            .addGroup(pnlSubcategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSubcategoriaLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(tfSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
        );

        pnlCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova categoria"));
        pnlCategoria.setOpaque(false);

        tfCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N
        tfCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCategoriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbReceita);
        rbReceita.setSelected(true);
        rbReceita.setText("Receita");
        rbReceita.setActionCommand("Receita");

        buttonGroup1.add(rbDespesa);
        rbDespesa.setText("Despesa");
        rbDespesa.setActionCommand("Despesa");

        btInserirCat.setText("Inserir");
        btInserirCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCategoriaLayout = new javax.swing.GroupLayout(pnlCategoria);
        pnlCategoria.setLayout(pnlCategoriaLayout);
        pnlCategoriaLayout.setHorizontalGroup(
            pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbReceita)
                .addGap(18, 18, 18)
                .addComponent(rbDespesa)
                .addGap(41, 41, 41)
                .addComponent(btInserirCat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(pnlCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCategoriaLayout.setVerticalGroup(
            pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriaLayout.createSequentialGroup()
                .addComponent(tfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserirCat)
                    .addComponent(rbDespesa)
                    .addComponent(rbReceita))
                .addGap(33, 33, 33))
        );

        tblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCategoria);

        tblSubcategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Subcategoria", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubcategoria);

        tfPesquisa.setForeground(new java.awt.Color(153, 153, 153));
        tfPesquisa.setToolTipText("");

        btPesquisaCategoria.setText("Pesquisar");
        btPesquisaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPesquisaCategoriaMouseClicked(evt);
            }
        });
        btPesquisaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaCategoriaActionPerformed(evt);
            }
        });

        btApagarCategoria.setText("Apagar");
        btApagarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarCategoriaActionPerformed(evt);
            }
        });

        tfPesquisaSub.setForeground(new java.awt.Color(153, 153, 153));

        btPesquisaSub.setText("Pesquisar");
        btPesquisaSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaSubActionPerformed(evt);
            }
        });

        btApagarSubcategoria.setText("Apagar");
        btApagarSubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarSubcategoriaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nexa Light", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRO DE PESSOAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pnlCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pnlSubcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btApagarCategoria)
                                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btPesquisaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)
                                        .addComponent(tfPesquisaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(354, 354, 354)
                                        .addComponent(btApagarSubcategoria)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPesquisaSub)))
                        .addGap(93, 93, 93))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPesquisaSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btPesquisaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btPesquisaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btApagarSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btApagarCategoria))
                .addGap(28, 28, 28))
        );

        jLayeredPane1.setLayer(bgImg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(bgImg)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(bgImg)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriasActionPerformed

    private void btInserirCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirCatActionPerformed
        Categoria categoria = new Categoria();
        categoria.setNomeCategoria(tfCategoria.getText());
        categoria.setTipoCategoria(buttonGroup1.getSelection().getActionCommand());

//        Subcategoria subcategoria = new Subcategoria();
//        subcategoria.setNomeSubcategoria(" ");
        ControleCategoria controle = new ControleCategoria();
        try {
            controle.salvar(categoria);
            JOptionPane.showMessageDialog(this, "Categoria salva!", "Concluído", JOptionPane.INFORMATION_MESSAGE);
            atualizarPesquisaCategoria();
            tfCategoria.setText("");//setando o campo em branco

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar o novo item.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btInserirCatActionPerformed

    private void btInserirSubcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirSubcatActionPerformed
        Subcategoria subcategoria = new Subcategoria();
        subcategoria.setNomeSubcategoria(tfSubcategoria.getText());
        subcategoria.setCategoriaId(cbCategorias.getSelectedIndex());
        ControleSubcategoria controle = new ControleSubcategoria();
        try {
            controle.salvar(subcategoria);
            JOptionPane.showMessageDialog(this, "Subcategoria salva!", "Concluído", JOptionPane.INFORMATION_MESSAGE);
            atualizarPesquisaSubcategoria();
            //setando o campo em branco
            tfSubcategoria.setText("");
            cbCategorias.setSelectedIndex(-1);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar o novo item.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btInserirSubcatActionPerformed

    private void tfCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCategoriaActionPerformed

    private void btPesquisaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisaCategoriaMouseClicked
        atualizarPesquisaCategoria();
    }//GEN-LAST:event_btPesquisaCategoriaMouseClicked

    private void btPesquisaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisaCategoriaActionPerformed

    private void btApagarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarCategoriaActionPerformed
        if (tblCategoria.getSelectedRow() >= 0) {
            Categoria categoriaSelecionada = resultadoPesquisaCategoria.get(tblCategoria.getSelectedRow());
            ControleCategoria controle = new ControleCategoria();
            try {
                controle.excluir(categoriaSelecionada);
                JOptionPane.showMessageDialog(this, "Item selecionado excluído!", "Concluído", JOptionPane.INFORMATION_MESSAGE);
                atualizarPesquisaCategoria();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao excluir o item selecionado.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btApagarCategoriaActionPerformed

    private void btPesquisaSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaSubActionPerformed
        atualizarPesquisaSubcategoria();        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisaSubActionPerformed

    private void btApagarSubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarSubcategoriaActionPerformed
        if (tblSubcategoria.getSelectedRow() >= 0) {
            Subcategoria subcategoriaSelecionada = resultadoPesquisaSub.get(tblSubcategoria.getSelectedRow());
            ControleSubcategoria controle = new ControleSubcategoria();
            try {
                controle.excluir(subcategoriaSelecionada);
                JOptionPane.showMessageDialog(this, "Item selecionado excluído!", "Concluído", JOptionPane.INFORMATION_MESSAGE);
                atualizarPesquisaSubcategoria();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao excluir o item selecionado.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btApagarSubcategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImg;
    private javax.swing.JButton btApagarCategoria;
    private javax.swing.JButton btApagarSubcategoria;
    private javax.swing.JButton btInserirCat;
    private javax.swing.JButton btInserirSubcat;
    private javax.swing.JButton btPesquisaCategoria;
    private javax.swing.JButton btPesquisaSub;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlCategoria;
    private javax.swing.JPanel pnlSubcategoria;
    private javax.swing.JRadioButton rbDespesa;
    private javax.swing.JRadioButton rbReceita;
    private javax.swing.JTable tblCategoria;
    private javax.swing.JTable tblSubcategoria;
    private javax.swing.JTextField tfCategoria;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JTextField tfPesquisaSub;
    private javax.swing.JTextField tfSubcategoria;
    // End of variables declaration//GEN-END:variables
}
