/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleTitulo;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Titulo;

/**
 *
 * @author macbook
 */
public class TitulosView extends javax.swing.JPanel {

    ArrayList<Titulo> resultadoPesquisa;
    Titulo tableTitulo = new Titulo();

    /**
     * Creates new form TitulosView
     */
    public TitulosView() {
        initComponents();
        atualizarPesquisa();
    }

    //--------------MÉTODOS-------------------
    private void atualizarPesquisa() {
        ControleTitulo controle = new ControleTitulo();
        DefaultTableModel model = (DefaultTableModel) tblTitulo.getModel();
        model.setNumRows(0);

        try {
            this.resultadoPesquisa = controle.pesquisar(tfPesquisa.getText().trim());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Falha na Pesquisa!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        for (Titulo titulo : this.resultadoPesquisa) {
            model.addRow(new Object[]{
                titulo.getIdTitulo(),
                titulo.getNomeTitulo(),
                titulo.getValorTitulo(),
                titulo.getCategoria().getNomeCategoria(),
                titulo.getSubCategoria().getNomeSubcategoria(),
                titulo.getTipoTitulo().getNomeTipoTitulo(),
                titulo.getNumeroParcela(),
                titulo.getDataVencimento(),
                titulo.getDataRealizacao(),
                titulo.getPendente(),
                titulo.getPessoa().getNomePessoa(),
                titulo.getCedente(),});
        }
    }

    private void filtro() {
        ControleTitulo controle = new ControleTitulo();
        DefaultTableModel model = (DefaultTableModel) tblTitulo.getModel();
        model.setNumRows(0);

        try {
            this.resultadoPesquisa = controle.pesquisarFiltro(Integer.toString(cbFiltro.getSelectedIndex()));
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Falha na Pesquisa!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        for (Titulo titulo : this.resultadoPesquisa) {
            model.addRow(new Object[]{
                titulo.getIdTitulo(),
                titulo.getNomeTitulo(),
                titulo.getValorTitulo(),
                titulo.getCategoria().getNomeCategoria(),
                titulo.getSubCategoria().getNomeSubcategoria(),
                titulo.getTipoTitulo().getNomeTipoTitulo(),
                titulo.getNumeroParcela(),
                titulo.getDataVencimento(),
                titulo.getDataRealizacao(),
                titulo.getPendente(),
                titulo.getPessoa().getNomePessoa(),
                titulo.getCedente(),});
        }
    }

    private void definirId() {
        if (tblTitulo.getSelectedRow() != -1) {
            int id = (int) tblTitulo.getValueAt(tblTitulo.getSelectedRow(), 0);
            UpdateView tela = new UpdateView();
            tela.setId(id);
            tela.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTitulo = new javax.swing.JTable();
        cbFiltro = new javax.swing.JComboBox<>();
        tfPesquisa = new javax.swing.JTextField();
        btPesquisa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTitulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Valor", "Categoria", "Subcategoria", "Tipo", "Parcela", "Vencimento", "Realizado", "Situação", "Responsável", "Cedente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTituloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTitulo);
        if (tblTitulo.getColumnModel().getColumnCount() > 0) {
            tblTitulo.getColumnModel().getColumn(0).setMinWidth(30);
            tblTitulo.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblTitulo.getColumnModel().getColumn(0).setMaxWidth(30);
            tblTitulo.getColumnModel().getColumn(1).setMinWidth(250);
            tblTitulo.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblTitulo.getColumnModel().getColumn(1).setMaxWidth(250);
            tblTitulo.getColumnModel().getColumn(2).setMinWidth(80);
            tblTitulo.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblTitulo.getColumnModel().getColumn(2).setMaxWidth(80);
            tblTitulo.getColumnModel().getColumn(5).setMinWidth(70);
            tblTitulo.getColumnModel().getColumn(5).setPreferredWidth(70);
            tblTitulo.getColumnModel().getColumn(5).setMaxWidth(70);
            tblTitulo.getColumnModel().getColumn(6).setMinWidth(60);
            tblTitulo.getColumnModel().getColumn(6).setPreferredWidth(60);
            tblTitulo.getColumnModel().getColumn(6).setMaxWidth(60);
            tblTitulo.getColumnModel().getColumn(9).setMinWidth(70);
            tblTitulo.getColumnModel().getColumn(9).setPreferredWidth(70);
            tblTitulo.getColumnModel().getColumn(9).setMaxWidth(70);
        }

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Despesa", "Receita", "Todos" }));
        cbFiltro.setSelectedIndex(-1);
        cbFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro por Tipo"));
        cbFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroActionPerformed(evt);
            }
        });

        tfPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro por Nome"));
        tfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaActionPerformed(evt);
            }
        });

        btPesquisa.setText("Pesquisa");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nexa Light", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONSULTA DE TÍTULOS");

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbFiltro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tfPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btAtualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisa)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(441, 441, 441))))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAtualizar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addGap(7, 7, 7))
        );

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgDesfocado.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaActionPerformed

    private void cbFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroActionPerformed
        if (cbFiltro.getSelectedIndex() <= 1) {
            filtro();
        } else {
            atualizarPesquisa();
        };
    }//GEN-LAST:event_cbFiltroActionPerformed

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        atualizarPesquisa();
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void tblTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTituloMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            definirId();
        }
    }//GEN-LAST:event_tblTituloMouseClicked

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atualizarPesquisa();
    }//GEN-LAST:event_btAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTitulo;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
