/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Toolkit;

/**
 *
 * @author edu_f
 */
public class TelaPrincipal extends javax.swing.JFrame {

    TelaPessoas cadastroPessoas;
    TelaCadastroTitulo cadastroCategorias;
    TelaTitulos cadastroTitulos;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {

        initComponents();
        this.setLocationRelativeTo(null);

        cadastroPessoas = null;
        cadastroCategorias = null;
        cadastroTitulos = null;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiPessoas = new javax.swing.JMenuItem();
        jmiCategorias = new javax.swing.JMenuItem();
        jmiTitulos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jMenu1.setText("Cadastros");

        jmiPessoas.setText("Pessoas");
        jmiPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPessoasActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPessoas);

        jmiCategorias.setText("Categorias");
        jmiCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCategoriasActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCategorias);

        jmiTitulos.setText("Títulos");
        jmiTitulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTitulosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiTitulos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPessoasActionPerformed

        if (cadastroPessoas == null) {
            cadastroPessoas = new TelaPessoas();
        }

        cadastroPessoas.setVisible(true);


    }//GEN-LAST:event_jmiPessoasActionPerformed

    private void jmiCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCategoriasActionPerformed

        if (cadastroCategorias == null) {
            cadastroCategorias = new TelaCadastroTitulo();
        }

        cadastroCategorias.setVisible(true);

    }//GEN-LAST:event_jmiCategoriasActionPerformed

    private void telasPraFrente() {
        if (cadastroPessoas != null) {
            if (cadastroPessoas.estaFechada()) {
                cadastroPessoas = null;
            } else {
                cadastroPessoas.setVisible(true);
                Toolkit.getDefaultToolkit().beep();
            }
        }
        if (cadastroCategorias != null) {
            if (cadastroCategorias.estaFechada()) {
                cadastroCategorias = null;
            } else {
                cadastroCategorias.setVisible(true);
                Toolkit.getDefaultToolkit().beep();
            }
        }        
        if (cadastroTitulos != null) {
            if (cadastroTitulos.estaFechada()) {
                cadastroTitulos = null;
            } else {
                cadastroTitulos.setVisible(true);
                Toolkit.getDefaultToolkit().beep();
            }           
        }
    }

    private void jmiTitulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTitulosActionPerformed

        if (cadastroTitulos == null) {
            cadastroTitulos = new TelaTitulos();
        }

        cadastroTitulos.setVisible(true);

    }//GEN-LAST:event_jmiTitulosActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        telasPraFrente();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiCategorias;
    private javax.swing.JMenuItem jmiPessoas;
    private javax.swing.JMenuItem jmiTitulos;
    // End of variables declaration//GEN-END:variables

}
