/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleCategoria;
import controle.ControleSubcategoria;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Subcategoria;

/**
 *
 * @author macbook
 */
public class CadastroCategoria extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCategoria
     */
    ArrayList<Categoria> resultadoPesquisaCategoria;
    ArrayList<Subcategoria> resultadoPesquisaSub;
    private boolean statusAberta;

    public CadastroCategoria() {
        initComponents();
        statusAberta = true;
        atualizarPesquisaCategoria();
        atualizarPesquisaSubcategoria();

    }

    public boolean estaFechada() {
        return !statusAberta;
    }

    private void atualizarPesquisaCategoria() {
        ControleCategoria controle = new ControleCategoria();
        DefaultTableModel model = (DefaultTableModel) tblCategoria.getModel();
        model.setNumRows(0);

        try {
            this.resultadoPesquisaCategoria = controle.pesquisar(tfPesquisa.getText().trim());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Falha na Pesquisa!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        for (Categoria categoria : this.resultadoPesquisaCategoria) {
            model.addRow(new Object[]{
                categoria.getNomeCategoria(),
                categoria.getTipoCategoria()
            });
        }
        //combo box de categorias p/ classificacao de subcategorias
        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
        List<Categoria> listaCategorias = resultadoPesquisaCategoria;
        for (int i = 0; i < listaCategorias.size(); i++) {
            cbCategorias.addItem(listaCategorias.get(i).getNomeCategoria());
        }

    }

    private void atualizarPesquisaSubcategoria() {
        ControleSubcategoria controle = new ControleSubcategoria();
        DefaultTableModel model = (DefaultTableModel) tblSubcategoria.getModel();
        model.setNumRows(0);

        try {
            this.resultadoPesquisaSub = controle.pesquisar(tfPesquisaSub.getText().trim());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Falha na Pesquisa!", "ERRO", JOptionPane.ERROR_MESSAGE);

        }
        for (Subcategoria subcategoria : this.resultadoPesquisaSub) {
            model.addRow(new Object[]{
                subcategoria.getNomeCategoriaSubcategoria(),
                subcategoria.getNomeSubcategoria(),
                subcategoria.getNomeTipoSubcategoria()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlAreaUtilBG1 = new javax.swing.JPanel();
        tfCategoria = new javax.swing.JTextField();
        cbCategorias = new javax.swing.JComboBox<>();
        lbTituloJanela = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();
        btInserirCat = new javax.swing.JButton();
        btInserirSubcat = new javax.swing.JButton();
        tfSubcategoria = new javax.swing.JTextField();
        btApagarCategoria = new javax.swing.JButton();
        rbReceita = new javax.swing.JRadioButton();
        rbDespesa = new javax.swing.JRadioButton();
        btApagarSubcategoria = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCategoria = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubcategoria = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btPesquisaCategoria = new javax.swing.JButton();
        tfPesquisa = new javax.swing.JTextField();
        tfPesquisaSub = new javax.swing.JTextField();
        btPesquisaSub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnlAreaUtilBG1.setBackground(new java.awt.Color(255, 255, 255));

        tfCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N

        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategorias.setSelectedIndex(-1);
        cbCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N
        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });

        lbTituloJanela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtCadastroCategorias.png"))); // NOI18N

        btFechar.setText("Fechar");
        btFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFecharMouseClicked(evt);
            }
        });

        btInserirCat.setText("Inserir");
        btInserirCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirCatActionPerformed(evt);
            }
        });

        btInserirSubcat.setText("Inserir");
        btInserirSubcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirSubcatActionPerformed(evt);
            }
        });

        tfSubcategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subcategoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nexa Light", 1, 12))); // NOI18N

        btApagarCategoria.setText("Apagar");
        btApagarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarCategoriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbReceita);
        rbReceita.setText("Receita");
        rbReceita.setActionCommand("Receita");

        buttonGroup1.add(rbDespesa);
        rbDespesa.setText("Despesa");
        rbDespesa.setActionCommand("Despesa");

        btApagarSubcategoria.setText("Apagar");
        btApagarSubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarSubcategoriaActionPerformed(evt);
            }
        });

        tblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCategoria);

        tblSubcategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Subcategoria", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubcategoria);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Nova Categoria:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Nova Subcategoria:");

        btPesquisaCategoria.setText("Pesquisar");
        btPesquisaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPesquisaCategoriaMouseClicked(evt);
            }
        });
        btPesquisaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaCategoriaActionPerformed(evt);
            }
        });

        tfPesquisa.setForeground(new java.awt.Color(153, 153, 153));
        tfPesquisa.setToolTipText("");

        tfPesquisaSub.setForeground(new java.awt.Color(153, 153, 153));

        btPesquisaSub.setText("Pesquisar");
        btPesquisaSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaSubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAreaUtilBG1Layout = new javax.swing.GroupLayout(pnlAreaUtilBG1);
        pnlAreaUtilBG1.setLayout(pnlAreaUtilBG1Layout);
        pnlAreaUtilBG1Layout.setHorizontalGroup(
            pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaUtilBG1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAreaUtilBG1Layout.createSequentialGroup()
                        .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(tfSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAreaUtilBG1Layout.createSequentialGroup()
                        .addComponent(tfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(rbReceita)
                        .addGap(29, 29, 29)
                        .addComponent(rbDespesa)))
                .addGap(0, 0, 0)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btInserirSubcat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserirCat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAreaUtilBG1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAreaUtilBG1Layout.createSequentialGroup()
                        .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btApagarCategoria)
                            .addComponent(tfPesquisa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(18, 18, 18)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAreaUtilBG1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaUtilBG1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaUtilBG1Layout.createSequentialGroup()
                                .addComponent(tfPesquisaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPesquisaSub)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaUtilBG1Layout.createSequentialGroup()
                                .addComponent(btApagarSubcategoria)
                                .addGap(195, 195, 195))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaUtilBG1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaUtilBG1Layout.createSequentialGroup()
                        .addComponent(lbTituloJanela)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaUtilBG1Layout.createSequentialGroup()
                        .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(341, 341, 341))))
        );
        pnlAreaUtilBG1Layout.setVerticalGroup(
            pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaUtilBG1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbTituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbReceita)
                    .addComponent(rbDespesa)
                    .addComponent(btInserirCat)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserirSubcat)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(116, 116, 116)
                .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAreaUtilBG1Layout.createSequentialGroup()
                        .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPesquisaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btApagarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAreaUtilBG1Layout.createSequentialGroup()
                        .addGroup(pnlAreaUtilBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPesquisaSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPesquisaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btApagarSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btFechar)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAreaUtilBG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAreaUtilBG1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFecharMouseClicked
        this.dispose();
        statusAberta = false;
    }//GEN-LAST:event_btFecharMouseClicked

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriasActionPerformed

    private void btApagarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarCategoriaActionPerformed
        if (tblCategoria.getSelectedRow() >= 0) {
            Categoria categoriaSelecionada = resultadoPesquisaCategoria.get(tblCategoria.getSelectedRow());
            ControleCategoria controle = new ControleCategoria();
            try {
                controle.excluir(categoriaSelecionada);
                JOptionPane.showMessageDialog(this, "Item selecionado excluído!", "Concluído", JOptionPane.INFORMATION_MESSAGE);
                atualizarPesquisaCategoria();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao excluir o item selecionado.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btApagarCategoriaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        statusAberta = false;
    }//GEN-LAST:event_formWindowClosed

    private void btPesquisaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisaCategoriaActionPerformed

    private void btPesquisaSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaSubActionPerformed
        atualizarPesquisaSubcategoria();        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisaSubActionPerformed

    private void btPesquisaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisaCategoriaMouseClicked
        atualizarPesquisaCategoria();
    }//GEN-LAST:event_btPesquisaCategoriaMouseClicked

    private void btInserirCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirCatActionPerformed
        Categoria categoria = new Categoria();

        categoria.setNomeCategoria(tfCategoria.getText());
        categoria.setTipoCategoria(buttonGroup1.getSelection().getActionCommand());
        ControleCategoria controle = new ControleCategoria();
        try {
            controle.salvar(categoria);
            JOptionPane.showMessageDialog(this, "Categoria salva!", "Concluído", JOptionPane.INFORMATION_MESSAGE);
            atualizarPesquisaCategoria();
            tfCategoria.setText("");//setando o campo em branco 
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar o novo item.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btInserirCatActionPerformed

    private void btInserirSubcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirSubcatActionPerformed
    Subcategoria subcategoria = new Subcategoria();

        subcategoria.setNomeSubcategoria(tfSubcategoria.getText());
        subcategoria.setCategoriaId(cbCategorias.getSelectedIndex());
        //subcategoria.setTipoCategoria(buttonGroup1.getSelection().getActionCommand());        
        ControleSubcategoria controle = new ControleSubcategoria();
        try {
            controle.salvar(subcategoria);
            JOptionPane.showMessageDialog(this, "Subcategoria salva!", "Concluído", JOptionPane.INFORMATION_MESSAGE);
            atualizarPesquisaSubcategoria();
            tfSubcategoria.setText("");//setando o campo em branco 
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar o novo item.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btInserirSubcatActionPerformed

    private void btApagarSubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarSubcategoriaActionPerformed
        if (tblSubcategoria.getSelectedRow() >= 0) {
            Subcategoria subcategoriaSelecionada = resultadoPesquisaSub.get(tblSubcategoria.getSelectedRow());
            ControleSubcategoria controle = new ControleSubcategoria();
            try {
                controle.excluir(subcategoriaSelecionada);
                JOptionPane.showMessageDialog(this, "Item selecionado excluído!", "Concluído", JOptionPane.INFORMATION_MESSAGE);
                atualizarPesquisaSubcategoria();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao excluir o item selecionado.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btApagarSubcategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApagarCategoria;
    private javax.swing.JButton btApagarSubcategoria;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btInserirCat;
    private javax.swing.JButton btInserirSubcat;
    private javax.swing.JButton btPesquisaCategoria;
    private javax.swing.JButton btPesquisaSub;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTituloJanela;
    private javax.swing.JPanel pnlAreaUtilBG1;
    private javax.swing.JRadioButton rbDespesa;
    private javax.swing.JRadioButton rbReceita;
    private javax.swing.JTable tblCategoria;
    private javax.swing.JTable tblSubcategoria;
    private javax.swing.JTextField tfCategoria;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JTextField tfPesquisaSub;
    private javax.swing.JTextField tfSubcategoria;
    // End of variables declaration//GEN-END:variables
}
